### ISSUE TITLE
Kylin account section => needs to fix private/public key parsing script

### ISSUE THREAD

**Issue by bezalel** [liquidapps-io/docs#6]
https://github.com/liquidapps-io/docs/blob/master/docs/developers/kylin-account.md

export ACTIVE_PRIVATE_KEY=`cat keys.json | jq -e '.keys.active_key.private'`
export ACTIVE_PUBLIC_KEY=`cat keys.json | jq -e '.keys.active_key.public'`

==>

export ACTIVE_PRIVATE_KEY=`cat keys.json | jq -e '.data.account.active.privateKey'`
export ACTIVE_PUBLIC_KEY=`cat keys.json | jq -e '.data.account.active.publicKey'`

**Comment by NatPDeveloper** [comment]
Thank you for this, I'll update the docs accordingly.
